config/routes.rb
Calendar::Application.routes.draw do
  resources :usuarios

  resources :orientadores do
    get :autocomplete_orientador_nome, :on => :collection
  end
  resources :tipo_usuarios
  resources :events
  resources :agendamentos
  resources :tipos
  resources :senha_resets

  match 'agendamento' => 'agendamento#index'
  match 'erro_criacao' => 'event#erro'
  match 'to_evento' => 'events#show_one'
  match 'escolha' => 'acessos#index'
  match 'sala_equipamento' => 'calendar#unico'
  match 'admin_novo_evento' => 'admin#new'
  match 'admin_evento_show' => 'admin#show'
  match 'admin_eventos' => 'tipos#eventos'
  match 'admin_rejeita' => 'admin_event#rejeita'
  match 'admin_aceita' => 'admin_event#aceita'
  match 'ver_usuario' => 'admin#ver_usuarios'
  match 'permissoes' => 'admin#permissoes'
  match 'permitir' => 'tipo_usuarios#edit'
  match 'ver_dia' => 'events#ver_dia'
  match 'ver_dia_adm' => 'events#ver_dia_adm'
  match 'monta_relatorio' => 'events#monta_relatorio'
  match 'monta_relatorio_adm' => 'events#monta_relatorio_adm'
  match 'newindex' => 'events#newindex'
  match 'login' => 'login#login'
  match 'logout' => 'login#logout'
  match 'permite_tudo' => 'usuarios#permite_tudo'
  match 'tirapermissao' =>'tipo_usuarios#destroy'
  match 'negar_tudo' => 'usuarios#negar_tudo'

  get "calendar/index"

  root :to => "calendar#index" #

end

app/views/admin/show.html.erb
<h2 align="center">Evento selecionado:</h2>

<% @agendamento = Agendamento.find(:all) %>
<% @event = Event.find(params[:id]) %>

<table id="tab_show_one" cellpadding="20" align="center">


  <tr class="par"><td>
    <b>Equipamento:</b>
    <% @tipo = Tipo.find(:all) %>
    <% @tipo.each do |t| %>
        <% if t.id == @event.tipo_id %>
            <%= t.nome %>
        <% end %>
    <% end %>
  </td></tr>

  <tr class="impar"><td>
    <b>Título:</b>
    <%= @event.title %>
  </td></tr>

  <tr class="par"><td>
    <b>Registrado para:</b>
    <%= @event.regpara %>
  </td></tr>

  <tr class="impar"><td>
    <b>Início em:</b>
    <%= @event.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
  </td></tr>

  <tr class="par"><td>
    <b>Término em:</b>
    <%= @event.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
  </td></tr>

  <tr class="par">
    <td><b>Descrição:</b>
    <%= @event.description %>
    </td></tr>
</table>

<p><%= link_to "voltar aos equipamentos", tipos_path   %></p>
<p><%= link_to "Voltar ao calendário", root_url   %></p>

app/views/admin/ver_usuarios.html.erb
<h1>Lista de usuarios:</h1>
<table>

  <tr>
    <td> Login</td>
    <td> Nome  </td>
    <td> Ultima atualização</td>

    <td></td>
  </tr>

  <% @usuario.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.nome %></td>
        <td><%= user.updated_at.strftime("%d/%m/%Y") %></td>

        <td><%= link_to 'Alterar permissões', :controller => 'tipo_usuarios', :action => 'new', :id => user.id    %></td>
      </tr>
  <% end %>

</table>


<p> <%= link_to "Criar novo usuario", new_usuario_path %></p>
<p> <%= link_to "voltar á tela inicial",  root_url %> </p>