config/routes.rb
Calendar::Application.routes.draw do
  resources :usuarios

  resources :orientadores do
    get :autocomplete_orientador_nome, :on => :collection
  end
  resources :tipo_usuarios
  resources :events
  resources :agendamentos
  resources :tipos
  resources :senha_resets

  match 'agendamento' => 'agendamento#index'
  match 'erro_criacao' => 'event#erro'
  match 'to_evento' => 'events#show_one'
  match 'escolha' => 'acessos#index'
  match 'sala_equipamento' => 'calendar#unico'
  match 'admin_novo_evento' => 'admin#new'
  match 'admin_evento_show' => 'admin#show'
  match 'admin_eventos' => 'tipos#eventos'
  match 'admin_rejeita' => 'admin_event#rejeita'
  match 'admin_aceita' => 'admin_event#aceita'
  match 'ver_usuario' => 'admin#ver_usuarios'
  match 'permissoes' => 'admin#permissoes'
  match 'permitir' => 'tipo_usuarios#edit'
  match 'ver_dia' => 'events#ver_dia'
  match 'ver_dia_adm' => 'events#ver_dia_adm'
  match 'monta_relatorio' => 'events#monta_relatorio'
  match 'monta_relatorio_adm' => 'events#monta_relatorio_adm'
  match 'newindex' => 'events#newindex'
  match 'login' => 'login#login'
  match 'logout' => 'login#logout'
  match 'permite_tudo' => 'usuarios#permite_tudo'
  match 'tirapermissao' =>'tipo_usuarios#destroy'
  match 'negar_tudo' => 'usuarios#negar_tudo'

  get "calendar/index"

  root :to => "calendar#index" #

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :tipo
  belongs_to :usuario
  has_many :agendamentos, :dependent => :destroy
  validates_presence_of :tipo_id

  def odiainteiro
    if self.all_day?
      "Sim"
    else
      "Nao"
    end
  end


  scope :before,
        lambda {|end_time| {:conditions => ["starts_at < ?", Event.format_date(end_time)] }}
  scope :after,
        lambda {|start_time| {:conditions => ["ends_at > ?", Event.format_date(start_time)] }}


  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
        :id => self.id,
        :title => self.title,
        #:description => self.description || "",
        :start => starts_at,
        #:end => ends_at,
        :recurring => false,
        :allDay => true,
        #:url => "http://watson.icb.usp.br/agendamento" << Rails.application.routes.url_helpers.event_path(id)
        :url => "http://localhost:3000" << Rails.application.routes.url_helpers.event_path(id)
        #:url => Rails.application.routes.url_helpers.event_path(id)        #redireciona para a página do evento quando clica no dia no calendario
    }
  end

  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  before_filter :usuario_autenticado?


  def index
    @u=session[:email]
    @events = Event.scoped(:select => ["events.*, tipos.nome, concat(ag.data_inicio, ' ', ag.hora_inicio) as starts_at,  concat(ag.data_fim, ' ', ag.hora_fim) as ends_at, concat(ag.inicio, ' ' , ag.fim, ' - ',  tipos.nome, ' - ', u.nome, ' - ramal ',u.ramal) as title "],:joins => ["events left join tipos on events.tipo_id= tipos.id inner join tipo_usuarios on tipos.id = tipo_usuarios.tipo_id  inner join usuarios u on events.usuario_id = u.id inner join agendamentos ag on ag.event_id = events.id "],  :order => [" tipos.nome, ag.data_inicio, ag.hora_inicio"]).uniq
    @event_tipo = @events

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.js  { render :json => @events }
    end
  end

  def newindex

    @u = session[:email]
    @events = Event.scoped(:select => ["events.*, ag.inicio, ag.fim, tipos.nome, concat(ag.data_inicio, ' ', ag.hora_inicio) as starts_at,  concat(ag.data_fim, ' ', ag.hora_fim) as ends_at, concat(ag.inicio, ' ' , ag.fim, ' - ',  tipos.nome, ' - ', u.nome, ' - ramal ',u.ramal) as title "],:joins => ["events left join tipos on events.tipo_id= tipos.id inner join tipo_usuarios on tipos.id = tipo_usuarios.tipo_id  inner join usuarios u on events.usuario_id = u.id inner join agendamentos ag on ag.event_id = events.id "],  :order => [" tipos.nome, ag.data_inicio, ag.hora_inicio"]).uniq
    @event_tipo = @events

    respond_to do |format|
      format.html
      format.xml  { render :xml => @events }
      format.js  { render :json => @events }
    end

  end

  # GET /events/1
  # GET /events/1.xml
  def show                                       # mostra os eventos
    @event = Event.find(params[:id],:order => ["tipo_id"])
    #@agendamento = Agendamento.find(:all, :conditions => params[:event_id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
      format.js { render :json => @event.to_json }
    end
  end

  def show_one                                   # mostra um unico evento
                                                 # mostra um unico agendamento
    @event = Event.find(:all)
    respond_to do |format|
      format.html # show_one.html.erb
      format.xml  { render :xml => "show_one" }
      format.js { render :json => "show_one" }
    end
  end

  def ver_dia
    @tipo = Tipo.find(:all)
    respond_to do |format|
      format.html # ver_dia.html.erb
      format.xml  { render :xml => "ver_dia" }
      format.js { render :json => "ver_dia" }
    end
  end

  def ver_dia_adm
    @tipo = Tipo.find(:all)
    respond_to do |format|
      format.html # ver_dia.html.erb
      format.xml  { render :xml => "ver_dia_adm" }
      format.js { render :json => "ver_dia_adm" }
    end
  end

  def monta_relatorio

    if params[:dia].blank? or params[:dia]["dia(1i)"].blank?
      @data =  nil
    else
      if params[:dia]["dia(2i)"].blank?
        @data = Date.new(y=params[:dia]["dia(1i)"].to_i)
      else
        if params[:dia]["dia(3i)"].blank?
          @data = Date.new(y=params[:dia]["dia(1i)"].to_i, m=params[:dia]["dia(2i)"].to_i)
        else
          @data = Date.new(y=params[:dia]["dia(1i)"].to_i, m=params[:dia]["dia(2i)"].to_i, d=params[:dia]["dia(3i)"].to_i)
        end
      end
    end

    if params[:sala].blank?
    	@tipo = nil
    else
    	@tipo = params[:sala]
    end

    @result = Event.find_by_sql(["select agendamentos.data_inicio, events.starts_at, events.ends_at,  events.tipo_id, events.regpara, events.description from events inner join agendamentos  on events.id = agendamentos.event_id where events.tipo_id = ? and agendamentos.data_inicio = ? ", @tipo, @data])

    respond_to do |format|
      format.html # monta_relatorio.html.erb
      format.xml { render :xml => @events }
      format.js  { render :json => @events }
    end

  end

  def monta_relatorio_adm
    @ano = params[:dia]["dia(1i)"].to_i
    @mes= params[:dia]["dia(2i)"].to_i
    if params[:sala].blank?
      @tipo = nil
    else
      @tipo = params[:sala]
    end
    @result = Event.find_by_sql(["select agendamentos.data_inicio, events.starts_at, events.ends_at,  events.tipo_id, events.regpara, events.description from events inner join agendamentos  on events.id = agendamentos.event_id where events.tipo_id = ? and month(agendamentos.data_inicio) = ? and year(agendamentos.data_inicio) = ? ", @tipo, @mes,@ano])
    respond_to do |format|
      format.html # monta_relatorio.html.erb
      format.xml { render :xml => @events }
      format.js  { render :json => @events }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new
    @t = Tipo.find(:all)
    @tu = TipoUsuario.find(:all)
    @usuario=session[:usuario]
    @tu.each do |tu|
      @t.each do |t|
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml

  #Funçao para criaçao de registros de eventos e de agendamento
  def create
    # cria um novo evento e todos os seus agendamentos

    @event = Event.new(params[:event])

    # acha todos os tipos
    tipo = Tipo.find(:all)
    tipo.each do |t|
      if t.id == @event.tipo_id
        if t.confirmacao == true   # marca o campo confirmação como true
          @event.pendente = true
        else
          @event.pendente = false  # marca o campo confirmação como false
        end
      end
    end


    if @event.save
      @event.usuario_id = session[:usuario]
      @event.u_email = session[:email]

      @inicio=Date.parse(@event.starts_at.to_s)    # cria uma string para a data e hora do inicio do evento
      @fim=Date.parse(@event.ends_at.to_s)

      @horainicio = @event.starts_at.to_datetime.strftime("%H:%M")
      @horafim = @event.ends_at.to_datetime.strftime("%H:%M")
      @i=@event.starts_at
      @f=@event.ends_at
      @diferenca=((@f - @i)/3600).round


# cria uma string para a data e hora do inicio do evento
# cria uma string para a data e hora do fim do evento
# compara as strings para saber se o evento tem um ou mais dias
# passa os parametros do agendamento e os salva no banco

      if @inicio != @fim
        respond_to do |format|
          format.html { render :action => "erro" }
          @event.destroy
        end
      else
        @agendamento = Agendamento.new
        @agendamento.data_inicio = @event.starts_at
        @agendamento.data_fim = @event.ends_at
        @agendamento.hora_inicio = @event.starts_at
        @agendamento.hora_fim = @event.ends_at
        @agendamento.event_id = @event.id
        @agendamento.tipo_id = @event.tipo_id
        @agendamento.inicio = @horainicio
        @agendamento.fim = @horafim
        @agendamento.save



        # Chama a funçao de validação, caso seja um evento conflitante destroy o que acabou de ser criado.
        valida

        # Envia email de confirmacao caso o evento fique pendente
        if @event.pendente == true
          @tipo = Tipo.find(:all)
          @tipo.each do |tipo|
            if tipo.id == @event.tipo_id
              AgPendente.email_agendamento(@event, tipo).deliver
            end
          end
        end

        # redireciona para a página correta
        respond_to do |format|
          #format.xml  { head :ok }
          #format.html # erro.html.erb

          if @a > 0  or @diferenca > 2
            format.html { render :action => "erro" }
            @event.destroy
          else
            if @event.pendente == true
              format.html { redirect_to(@event, :notice => 'Evento criado com sucesso. Por favor aguarde o evento ser confirmado pelo administrador da sala.') }
              format.xml  { render :xml => @event, :status => :created, :location => @event }
            else
              format.html { redirect_to(@event, :notice => 'Evento criado com sucesso.') }
              format.xml  { render :xml => @event, :status => :created, :location => @event }
            end
          end

        end
      end
    end
  end


# PUT /events/1
# PUT /events/1.xml
# PUT /events/1.js
# when we drag an event on the calendar (from day to day on the month view, or stretching
# it on the week or day view), this method will be called to update the values.
# viv la REST!
  def update
    #Para atualizaçao do evento tem que continuar respeitando a regra de salvar baseado nos dias da semana
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])

        # acha todos os tipos
        tipo = Tipo.find(:all)
        tipo.each do |t|
          if t.id == @event.tipo_id
            if t.confirmacao == true   # marca o campo confirmação como true
              @event.pendente = true
            else
              @event.pendente = false  # marca o campo confirmação como false
            end
          end
        end

        @agendamento = Agendamento.where(:event_id => @event.id)
        @agendamento.each do |ag|
          ag.destroy
        end
        @inicio=Date.parse(@event.starts_at.to_s)
        @fim=Date.parse(@event.ends_at.to_s)

        @horainicio = @event.starts_at.to_datetime.strftime("%H:%M")
        @horafim = @event.ends_at.to_datetime.strftime("%H:%M")
        @i=@event.starts_at
        @f=@event.ends_at
        @diferenca=((@f - @i)/3600).round

        if @inicio != @fim
          respond_to do |format|
            format.html { render :action => "erro" }
            @event.destroy
          end
        else
          @agendamento = Agendamento.new
          @agendamento.data_inicio = @event.starts_at
          @agendamento.data_fim = @event.ends_at
          @agendamento.hora_inicio = @event.starts_at

app/views/events/create.html.erb
<h2> Falta a associação do equipamento</h2>
<%=  link_to "Voltar", root_path %>

app/views/events/edit.html.erb
<h1>Editando evento</h1>

<%= render 'form_edit' %>

<%= link_to 'Mostrar', @event %> |
<%= link_to 'Voltar', newindex_path %>

app/views/events/erro.html.erb
<script type="text/JavaScript">
  alert("O evento não pode ser criado.")
</script>
<h1>Erro na criação do evento.</h1>

<p>O evento não pode ser criado pois o equipamento escolhido estará sendo usada nesse momento.<br/>
Por favor escolha outro dia ou horário.</p>

<br/>
<%= link_to 'ver calendario', calendar_index_path %>
<br/>
<%= link_to 'Novo Evento', new_event_path %>

app/views/events/index.html.erb
<h1 id="events">Listando  eventos</h1>



<table id="tabela_index" cellpadding="3" cellspacing="3" align="center">
  <tr>
    <th class="t1">Tipo</th>
    <th class="t1">Titulo</th>
    <th class="t1">Início</th>
    <th class="t1">Fim</th>
    <th class="t1"></th>
    <th class="t1"></th>
  </tr>

  <% for event in @event_tipo %>


      <tr>
        <td class="t1"><%= event.nome %></td>
        <td class="t1"><%= event.title %></td>
        <td class="t1"><%= event.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="t1"><%= event.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="t1"><%= link_to 'Mostrar', :controller => 'events', :action => 'show_one', :id => event.id %></td>
        <% if @usuario.email == event.u_email %>
            <td class="t1"><%= link_to 'Editar', edit_event_path(event) %></td>
            <td class="t1"><%= link_to 'Excluir', event, method: :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>
<div id="rodape" align="center">
  <%= link_to 'ver calendario', calendar_index_path %> |
  <%= link_to 'Novo Evento', new_event_path %>
</div>

app/views/events/indexold.html.erb
<h1 id="events">Listando  eventos</h1>



<table id="tabela_index" cellpadding="3" cellspacing="3" align="center">
  <tr>
    <th class="t1">Tipo</th>
    <th class="t1">Titulo</th>
    <th class="t1">Registrado para</th>
    <th class="t1">Início</th>
    <th class="t1">Fim</th>
    <th class="t1">Descrição</th>
    <th class="t1"></th>
    <th class="t1"></th>
  </tr>

  <% for event in @event_tipo %>


      <tr>
        <td class="t1"><%= event.nome %></td>
        <td class="t1"><%= event.title %></td>
        <td class="t1"><%= event.regpara  %></td>
        <td class="t1"><%= event.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="t1"><%= event.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %></td>
        <td class="t1"><%= event.description %></td>
        <td class="t1"><%= link_to 'Mostrar', :controller => 'events', :action => 'show_one', :id => event.id %></td>
        <% if @usuario.email == event.u_email %>
            <td class="t1"><%= link_to 'Editar', edit_event_path(event) %></td>
            <td class="t1"><%= link_to 'Excluir', event, method: :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>

<br/>
<div id="rodape" align="center">
  <%= link_to 'Ver calendario', calendar_index_path %> |
  <%= link_to 'Novo Agendamento', new_event_path %>
</div>

app/views/events/monta_relatorio.html.erb
<% if session[:usuario] %>
    <!-- busca os agendamentos e cria a variavel para ser comparada -->

    <h1 id="events">Lista de Agendamentos do dia</h1>

    <div id='evento'>
    <table cellpadding="5" cellspacing="5" border="2" align="center">

        <tr>
            <td><b>Data:</b></td>
            <td><b>Equipamento:</b></td>
            <td><b>In&iacute;cio em:</b></td>
            <td><b>T&iacute;tulo:</b></td>
            <td><b>Registrado para:</b></td>
            <td><b>Descri&ccedil;&atilde;o:</b></td>

        </tr>
        <% @result.each do |r| %>
            <tr>
                <td><%= r.data_inicio.to_datetime.strftime("%d/%m/%Y") %></td>
                <td>
                    <% @tipos = Tipo.find(:all) %>
                    <% @tipos.each do |t| %>
                        <% if t.id == r.tipo_id %>
                            <%= t.nome %>
                        <% end %>
                    <% end %>
                </td>
                <td><b><%= r.starts_at.to_datetime.strftime("%H:%M") %></b></td>
                <td><b><%= r.ends_at.to_datetime.strftime("%H:%M") %></b></td>
                <td><%= r.regpara %></td>
                <td><%= r.description %></td>
            </tr>
        <% end %>
    </table>
    </div>
    <br><br>
    <div id="rodape" align="center">
        <%= link_to 'Ver calendario', calendar_index_path %> |
        <%= link_to "Voltar",:controller =>'events', :action=>'ver_dia'%>
    </div>
<% end %>

app/views/events/monta_relatorio_adm.html.erb
<% if session[:usuario] %>
    <!-- busca os agendamentos e cria a variavel para ser comparada -->

    <h1 id="events">Lista de Agendamentos </h1>

    <div id='evento'>
    <table cellpadding="5" cellspacing="5" border="2" align="center">

        <tr>
            <td><b>Data:</b></td>
            <td><b>Equipamento:</b></td>
            <td><b>In&iacute;cio em:</b></td>
            <td><b>Fim:</b></td>
            <td><b>Registrado para:</b></td>
            <td><b>Descri&ccedil;&atilde;o:</b></td>

        </tr>
        <% @result.each do |r| %>
            <tr>
                <td><%= r.data_inicio.to_datetime.strftime("%d/%m/%Y") %></td>
                <td>
                    <% @tipos = Tipo.find(:all) %>
                    <% @tipos.each do |t| %>
                        <% if t.id == r.tipo_id %>
                            <%= t.nome %>
                        <% end %>
                    <% end %>
                </td>
                <td><b><%= r.starts_at.to_datetime.strftime("%H:%M") %></b></td>
                <td><b><%= r.ends_at.to_datetime.strftime("%H:%M") %></b></td>
                <td><%= r.regpara %></td>
                <td><%= r.description %></td>
            </tr>
        <% end %>
    </table>
    </div>
    <br><br>
    <div id="rodape" align="center">
        <%= link_to 'Ver calendario', calendar_index_path %> |
        <%= link_to "Voltar",:controller =>'events', :action=>'ver_dia_adm'%>
    </div>
<% end %>

app/views/events/new.html.erb
<h1>Novo  Agendamento</h1>

<%= render 'form' %>
<%= link_to 'Voltar', calendar_index_path %>

app/views/events/show.html.erb
<% if session[:type_id] == 1 %>
    <!-- busca os agendamentos e cria a variavel para ser comparada -->
    <h1 id="events">Eventos do dia.</h1>

    <% agendamento = Agendamento.find(:all, :order => 'tipo_id, hora_inicio') %>

    <table cellpadding="5" cellspacing="5" border="2" align="center">
      <tr>
        <td><b>Equipamento:</b></td>
        <td><b>Data inicial:</b></td>
        <td><b>Data final:</b></td>
        <td><b>Horário Inicial:</b></td>
        <td><b>Horário final:</b></td>
        <td><b>Registrado para:</b></td>
        <td><b>Descrição:</b></td>

      </tr>


      <%agendamento.each do |agen| %>

          <!-- compara a variavel para achar os agendamentos do dia selecionado -->
          <%if agen.data_inicio.to_datetime.strftime("%d/%m/%Y") == @event.starts_at.to_datetime.strftime("%d/%m/%Y") %>

              <!-- busca no campo Events os eventos do dia selecionado e retorna para o html os valores necessários -->
              <% event = Event.find(:all) %>

              <% event.each do|ev| %>
                  <% if ev.id == agen.event_id %>
                      <tr>
                        <td>
                          <% @tipo = Tipo.find(:all) %>
                          <% @tipo.each do |t| %>
                              <% if t.id == ev.tipo_id %>
                                  <%= t.nome %>
                              <% end %>
                          <% end %>
                        </td>

                        <td><%= ev.starts_at.to_datetime.strftime("%d/%m/%Y") %></td>

                        <td><%= ev.ends_at.to_datetime.strftime("%d/%m/%Y") %></td>

                        <td><b><%= ev.starts_at.to_datetime.strftime("%H:%M") %></b></td>

                        <td><b><%= ev.ends_at.to_datetime.strftime("%H:%M") %></b></td>


                        <td><%= ev.regpara %></td>



                        <td><%= ev.description %></td>
                      </tr>
                  <% end %>
              <% end %>
          <% end %>
      <% end %>
    </table>
    <br><br>
    <div id="rodape" align="center">
      <!--< %= link_to 'Voltar', events_path %> | -->
      <%= link_to 'ver calendario', calendar_index_path %> |
      <%= link_to 'Novo Evento', new_event_path %>
    </div>

<% elsif session[:type_id] == 0 %>
    <!-- busca os agendamentos e cria a variavel para ser comparada -->




    <% agendamento = Agendamento.find(:all, :order => 'tipo_id, hora_inicio') %>
    <table cellpadding="5" cellspacing="5" border="2" align="center">
      <tr>
        <td><b>Sala:</b></td>
        <td><b>Data inicial:</b></td>
        <td><b>Data final:</b></td>
        <td><b>Horário Inicial:</b></td>
        <td><b>Horário final:</b></td>
        <td><b>Registrado para:</b></td>
        <td><b>Descrição:</b></td>

      </tr>


      <%agendamento.each do |agen| %>

          <!-- compara a variavel para achar os agendamentos do dia selecionado -->
          <%if agen.data_inicio.to_datetime.strftime("%d/%m/%Y") == @event.starts_at.to_datetime.strftime("%d/%m/%Y") %>

              <!-- busca no campo Events os eventos do dia selecionado e retorna para o html os valores necessários -->
              <% event = Event.find(:all) %>

              <% event.each do|ev| %>
                  <% if ev.id == agen.event_id %>
                      <tr>
                        <td>
                          <% @tipo = Tipo.find(:all) %>
                          <% @tipo.each do |t| %>
                              <% if t.id == ev.tipo_id %>
                                  <%= t.nome %>
                              <% end %>
                          <% end %>
                        </td>

                        <td><%= ev.starts_at.to_datetime.strftime("%d/%m/%Y") %></td>

                        <td><%= ev.ends_at.to_datetime.strftime("%d/%m/%Y") %></td>

                        <td><b><%= ev.starts_at.to_datetime.strftime("%H:%M") %></b></td>

                        <td><b><%= ev.ends_at.to_datetime.strftime("%H:%M") %></b></td>

                        <td><%= ev.regpara %></td>


                        <td><%= ev.description %></td>
                      </tr>
                  <% end %>
              <% end %>
          <% end %>
      <% end %>
    </table>
    <br><br>


    <div id="rodape" align="center">
      <%= link_to 'Ver calendario', calendar_index_path %> |
      <%= link_to 'Novo agendamento', new_event_path %>
    </div>
<% end %>

app/views/events/show_one.html.erb
<% if session[:type_id]== 1 %>

    <p id="notice"><%= notice %></p>

    <h1 id="events">Mostrando evento:</h1>

    <% @event = Event.find(params[:id]) %>
        <table id="tab_show_one" cellpadding="8">

        <tr>
            <td>
                <b>Equipamento:</b>
                <% @tipo = Tipo.find(:all) %>
                <% @tipo.each do |t| %>
                    <% if t.id == @event.tipo_id %>
                        <%= t.nome %>
                    <% end %>
                <% end %>
            </td>
        </tr>

        <tr>
            <td>
                <b>Registrado para:</b>
                <%= @event.regpara %>
            </td>
        </tr>

        <tr>
            <td>
                <b>Início em:</b>
                <%= @event.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
            </td>
        </tr>

        <tr>
            <td>
                <b>Término em:</b>
                <%= @event.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
            </td>
        </tr>



        <tr>
            <td>
                <b>Descrição:</b>
                <%= @event.description %>
            </td>
        </tr>
    </table>
    <br><br>
    <div id="rodape">
        <%= link_to 'Voltar', calendar_index_path %>
    </div>
<% elsif session[:type_id] == 0 %>
    <p id="notice"><%= notice %></p>

    <h1 id="events">Mostrando evento</h1>

    <% @event = Event.find(params[:id]) %>
    <table id="tab_show_one" cellpadding="20">

        <tr class="par">
            <td>
                <b>Equipamento:</b>
                <% @tipo = Tipo.find(:all) %>
                <% @tipo.each do |t| %>
                    <% if t.id == @event.tipo_id %>
                        <%= t.nome %>
                    <% end %>
                <% end %>
            </td>
        </tr>



        <tr class="impar">
            <td>
                <b>Registrado para:</b>
                <%= @event.regpara %>
            </td>
        </tr>

        <tr class="par">
            <td>
                <b>Início em:</b>
                <%= @event.starts_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
            </td>
        </tr>

        <tr class="impar">
            <td>
                <b>Término em:</b>
                <%= @event.ends_at.to_datetime.strftime("%d/%m/%Y %H:%M") %>
            </td>
        </tr>


        <tr class="par">
            <td>
                <b>Descrição:</b>
                <%= @event.description %>
            </td>
        </tr>


    </table>
    <br><br>
    <div id="rodape">
        <%= link_to 'Voltar', calendar_index_path %>
    </div>
<% end %>

app/views/events/ver_dia.html.erb
<fieldset>
    <legend>Verifique os eventos do dia equipamento:</legend>
    <%= form_tag :action => 'monta_relatorio' do %>
        <div class="field">
          <%= label_tag("Data") %>
          <%= date_select 'dia','dia' %>
        </div>
        <div class="field">
            <% @u = session[:usuario] %>
            <% @array = [] %>       <!-- cria um array que passa os parametros para a busca -->
            <% @sel = [] %>

            <% Tipo.find(:all).each do |t| %>           <!-- acha todos os tipos -->

              <% TipoUsuario.find(:all).each do |tu| %>                    <!-- acha os tipos em que o usuario pode  -->
                  <% if t.id == tu.tipo_id && @u == tu.usuario_id %>    <!--  fazer seus agendamentos -->

                      <% @array.push [t.nome, t.id]%>       <!-- recebe os valores do array -->

                      <% break %>                           <!-- quebra o loop -->
                  <% end %>
              <% end %>
            <% end %>
            <%= label_tag("Agendamento") %>
            <% @array.each do |tipotodos| %>
                <% @sel.push  tipotodos %>
            <%end%>
            <%= select_tag(:sala, options_for_select(@sel))%>        <!-- cria o combobox com os valores do array -->
            <br>
            <br>
            <div class="actions">
                <%= submit_tag "Buscar" %>
            </div>
         </div>

    <% end %>
  <%= link_to 'Voltar', calendar_index_path %>
</fieldset>