config/routes.rb
Calendar::Application.routes.draw do
  resources :usuarios

  resources :orientadores do
    get :autocomplete_orientador_nome, :on => :collection
  end
  resources :tipo_usuarios
  resources :events
  resources :agendamentos
  resources :tipos
  resources :senha_resets

  match 'agendamento' => 'agendamento#index'
  match 'erro_criacao' => 'event#erro'
  match 'to_evento' => 'events#show_one'
  match 'escolha' => 'acessos#index'
  match 'sala_equipamento' => 'calendar#unico'
  match 'admin_novo_evento' => 'admin#new'
  match 'admin_evento_show' => 'admin#show'
  match 'admin_eventos' => 'tipos#eventos'
  match 'admin_rejeita' => 'admin_event#rejeita'
  match 'admin_aceita' => 'admin_event#aceita'
  match 'ver_usuario' => 'admin#ver_usuarios'
  match 'permissoes' => 'admin#permissoes'
  match 'permitir' => 'tipo_usuarios#edit'
  match 'ver_dia' => 'events#ver_dia'
  match 'ver_dia_adm' => 'events#ver_dia_adm'
  match 'monta_relatorio' => 'events#monta_relatorio'
  match 'monta_relatorio_adm' => 'events#monta_relatorio_adm'
  match 'newindex' => 'events#newindex'
  match 'login' => 'login#login'
  match 'logout' => 'login#logout'
  match 'permite_tudo' => 'usuarios#permite_tudo'
  match 'tirapermissao' =>'tipo_usuarios#destroy'
  match 'negar_tudo' => 'usuarios#negar_tudo'

  get "calendar/index"

  root :to => "calendar#index" #

end

app/controllers/orientadores_controller.rb
class OrientadoresController < ApplicationController


  # GET /orientadores
  # GET /orientadores.xml


  autocomplete :orientador, :nome

  def index
    @orientadores = Orientador.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @orientadores }
    end
  end

  # GET /orientadores/1
  # GET /orientadores/1.xml
  def show
    @orientador = Orientador.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @orientador }
    end
  end

  # GET /orientadores/new
  # GET /orientadores/new.xml
  def new
    @orientador = Orientador.new


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @orientador }
    end
  end

  # GET /orientadores/1/edit
  def edit
    @orientador = Orientador.find(params[:id])
  end

  # POST /orientadores
  # POST /orientadores.xml
  def create
    @orientador = Orientador.new(params[:orientador])

    respond_to do |format|
      if @orientador.save
        format.html { redirect_to(@orientador, :notice => 'Orientador foi criado com sucesso.') }
        format.xml  { render :xml => @orientador, :status => :created, :location => @orientador }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @orientador.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orientadores/1
  # PUT /orientadores/1.xml
  def update
    @orientador = Orientador.find(params[:id])

    respond_to do |format|
      if @orientador.update_attributes(params[:orientador])
        format.html { redirect_to(@orientador, :notice => 'Orientador foi atualizado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @orientador.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orientadores/1
  # DELETE /orientadores/1.xml
  def destroy
    @orientador = Orientador.find(params[:id])
    @orientador.destroy

    respond_to do |format|
      format.html { redirect_to(orientadores_url) }
      format.xml  { head :ok }
    end
  end



end

app/helpers/orientadores_helper.rb
module OrientadoresHelper
end

app/views/orientadores/_form.html.erb
<%= form_for(@orientador) do |f| %>
  <% if @orientador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orientador.errors.count, "error") %> impediram esse cadastro:</h2>

      <ul>
      <% @orientador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>


  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :departamento, "Departamento" %>  <br>
    <%= f.text_field :departamento %>
  </div>


  <div class="actions">
    <%= f.submit "Enviar" %>
  </div>

<% end %>

app/views/orientadores/edit.html.erb
<h1>Ediando orientadores</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @orientador %> |
<%= link_to 'Voltar', orientadores_path %>

app/views/orientadores/index.html.erb
<h1>Listando orientadores</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Departamento</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orientadores.each do |orientador| %>
  <tr>
    <td><%= orientador.nome %></td>
    <td><%= orientador.email %></td>
    <td><%= orientador.departamento %></td>
    <td><%= link_to 'Mostrar', orientador %></td>
    <td><%= link_to 'Editar', edit_orientador_path(orientador) %></td>
    <td><%= link_to 'Apagar', orientador, :confirm => 'Tem certeza?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<p><%= link_to 'Novo Orientador', new_orientador_path %>   </p>
<p><%= link_to "Voltar" , calendar_index_path %> </p>

app/views/orientadores/new.html.erb
<h1>Novo orientador</h1>

<%= render 'form' %>

<%= link_to 'Voltar', orientadores_path %>

app/views/orientadores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @orientador.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @orientador.email %>
</p>

<p>
  <b>Departamento:</b>
  <%= @orientador.departamento %>
</p>


<%= link_to 'Editar', edit_orientador_path(@orientador) %> |
<%= link_to 'Voltar', orientadores_path %>